#!/usr/bin/env python3

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path


CLDR_URL = (
    "https://raw.githubusercontent.com/unicode-org/cldr-json/"
    "48.2.1/cldr-json/cldr-annotations-full/"
    "annotations/en/annotations.json"
)

ROOT = Path(__file__).resolve().parents[1]

EMOJI_DATA = ROOT / "src/popups/emoji/EmojiData.qml"
OUTPUT = ROOT / "src/popups/emoji/EmojiSearchData.qml"


def normalize_emoji(value: str) -> str:
    """
    CLDR's annotation data can differ from local emoji strings
    in whether U+FE0F (variation selector-16) is present.
    Remove it for matching only.
    """
    return value.replace("\ufe0f", "")


def load_current_emojis() -> list[tuple[str, str]]:
    """
    Extract every emoji and its category from EmojiData.qml.
    Returns:
        [(emoji, category), ...]
    """
    text = EMOJI_DATA.read_text(encoding="utf-8")

    categories = re.findall(
        r"""
        label:\s*"([^"]+)"
        .*?
        emojis:\s*\[(.*?)\]
        """,
        text,
        flags=re.DOTALL | re.VERBOSE,
    )

    if not categories:
        raise RuntimeError(
            f"Could not parse emoji categories from {EMOJI_DATA}"
        )

    result: list[tuple[str, str]] = []
    seen: set[str] = set()

    for category, emoji_block in categories:
        emojis = re.findall(r'"([^"]*)"', emoji_block)

        for emoji in emojis:
            if emoji not in seen:
                seen.add(emoji)
                result.append((emoji, category))

    if not result:
        raise RuntimeError(
            f"No emojis were found in {EMOJI_DATA}"
        )

    return result


def download_cldr() -> dict:
    print("Downloading CLDR emoji annotations...")

    request = urllib.request.Request(
        CLDR_URL,
        headers={
            "User-Agent": "quickshell-emoji-data-generator/1.0"
        },
    )

    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def build_annotation_lookup(data: dict) -> dict[str, dict]:
    annotations = data["annotations"]["annotations"]

    lookup: dict[str, dict] = {}

    for emoji, entry in annotations.items():
        lookup[normalize_emoji(emoji)] = entry

    return lookup


def escape_qml_string(value: str) -> str:
    """
    JSON string syntax is valid JavaScript/QML string syntax,
    while correctly escaping quotes, backslashes, etc.
    """
    return json.dumps(value, ensure_ascii=False)


def main() -> int:
    emojis = load_current_emojis()
    cldr = download_cldr()
    lookup = build_annotation_lookup(cldr)

    generated: dict[str, str] = {}
    missing: list[tuple[str, str]] = []

    for emoji, category in emojis:
        annotation = lookup.get(normalize_emoji(emoji))

        if annotation:
            name = annotation.get("tts", [""])[0]

            keywords = annotation.get("default", [])

            terms = " ".join(
                [name, *keywords, category]
            ).lower()

        else:
            # Keep the emoji searchable by its category even if
            # CLDR has no annotation for a particular sequence.
            terms = category.lower()
            missing.append((emoji, category))

        generated[emoji] = terms

    lines: list[str] = [
        "import QtQuick",
        "",
        "// This file is generated by tools/generate_emoji_search_data.py",
        "// Source: Unicode CLDR English emoji annotations.",
        "// Do not edit manually.",
        "",
        "QtObject {",
        "    readonly property var terms: ({",
    ]

    entries = list(generated.items())

    for index, (emoji, terms) in enumerate(entries):
        comma = "," if index < len(entries) - 1 else ""

        lines.append(
            f"        {escape_qml_string(emoji)}: "
            f"{escape_qml_string(terms)}{comma}"
        )

    lines.extend([
        "    })",
        "}",
        "",
    ])

    OUTPUT.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    print(f"Generated: {OUTPUT}")
    print(f"Indexed emojis: {len(generated)}")

    if missing:
        print()
        print(
            f"Warning: {len(missing)} emoji had no direct CLDR annotation."
        )

        for emoji, category in missing[:20]:
            print(f"  {emoji} ({category})")

        if len(missing) > 20:
            print(f"  ... and {len(missing) - 20} more")

    return 0


if __name__ == "__main__":
    sys.exit(main())
